In [1]:
import pandas as pd
import os

In [ ]:
files = [f for f in os.listdir('.') if os.path.isfile(f)]
for f in files:
    # do something

In [2]:
df = pd.read_csv('02-07-20-beauty-and-the-beast.csv')

In [3]:
df.head()

,Board,Qty,Name,Printing,Foil,Alter,Signed,Condition,Language,Commander
0,main,1,"Adeline, Resplendent Cathar",MID,NaN,NaN,NaN,NaN,NaN,NaN
1,main,1,Angel of Glory's Rise,AVR,NaN,NaN,NaN,NaN,NaN,NaN
2,main,1,Anointed Procession,AKH,NaN,NaN,NaN,NaN,NaN,NaN
3,main,1,Arcane Signet,C20,NaN,NaN,NaN,NaN,NaN,NaN
4,main,1,Arid Mesa,MM3,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
cards = df[['Name']]

In [5]:
cards.head()

                          Name
0  Adeline, Resplendent Cathar
1        Angel of Glory's Rise
2          Anointed Procession
3                Arcane Signet
4                    Arid Mesa

In [8]:
df_2 = pd.read_csv('02-07-20-monster-mash.csv')

In [9]:
df_2.head()

,Board,Qty,Name,Printing,Foil,Alter,Signed,Condition,Language,Commander
0,maybe,1,Abandon Reason,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,maybe,1,Aetherflux Reservoir,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,maybe,1,Alms of the Vein,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,main,1,Altar of Dementia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,main,1,Ancient Craving,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
cards_2 = df_2[['Name']]

In [11]:
cards_2.tail()

                   Name
191      Warstorm Surge
192   Wayfarer's Bauble
193      Whip of Erebos
194  Zombie Infestation
195             Zombify

In [12]:
dfs = [cards, cards_2]
total_cards = pd.concat(dfs)

In [15]:
files = [f for f in os.listdir('.') if os.path.isfile(f)]
for f in files:
    filename = str(f)
    print(filename)
    if (not (filename == "Card Manipulation.ipynb")):
        more_cards = pd.read_csv(filename)
        more_cards = more_cards[['Name']]
        dfs = [total_cards, more_cards]
        total_cards = pd.concat(dfs)

02-07-20-beauty-and-the-beast.csv
02-07-20-monster-mash.csv
03-01-17-the-manliest-95-land-edh-deck-youll-ever-see-c.csv
05-02-19-yasova-dragonclaw.csv
06-02-20-mono-green-enchantress.csv
08-12-15-sacrificial-lamb.csv
13-12-20-rakdos.csv
15-03-19-midsummer-nights-dream.csv
17-08-19-atraxa.csv
18-04-21-thassa-flicker.csv
18-07-17-titania-edh.csv
19-02-15-teysa.csv
19-02-20-rhyss-pieces.csv
2-spooky-2.csv
20-02-17-spooders.csv
21-01-20-ocean-man.csv
22-12-17-zurgo-edh.csv
29-07-19-omnath-locus-of-mana.csv
a-good-day-to-die-1.csv
accursed-potions-and-twisted-notions.csv
aguamenti.csv
alela-all-the-things.csv
alela-artificial-eggs.csv
alela-constellation-1.csv
attack-of-the-hogaak.csv
backstreet-elves.csv
bruna-i-swear-i-dont-run-enchantments.csv
built-from-scratch-upgrade.csv
Card Manipulation.ipynb
cerberus-the-guard-dog-of-hades.csv
cheapskate-competitive-talrand-budget-100.csv
competitive-taigam-deck-persistent-petitioners.csv
dagsson-into-the-myrverse.csv
dagsson-transformers.csv
damia-mill-battlecruiserdreamcrusher.csv
divine-machinations-cleric-tribal.csv
double-trouble-edh.csv
dr-volrath-will-see-you-now.csv
eldrazi-lost-but-found.csv
enbantment-overhaul-1.csv
ephara-remastered.csv
every-masochist-needs-a-marchesa-to-love-them.csv
ezuri-renegade-leader-combo-elves-primer.csv
fish-inc.csv
flick-o-rama-yorion-casually-competitive.csv
gaddock-teeg-creature-crontrol.csv
gadwicks-frozen-hell.csv
giver-of-bad-gifts-zedruu-edh-copy-4.csv
goth-tinkerbell.csv
gothyeen (1).csv
gothyeen.csv
grismolds-plants-and-tokens.csv
gw-survey-corps.csv
gym-leader-mayael-wants-to-battle.csv
haktos-strikes-sometimes-twice.csv
hanna-tunnel-vision.csv
hogaaks-legion.csv
im-either-crazy-aura-genius.csv
im-the-reason-people-hate-child-of-alara.csv
infinite-knowledge-infinite-power-psz-goodstuff.csv
infinite-mana-finite-decks.csv
its-tough-to-be-xenagod (1).csv
its-tough-to-be-xenagod.csv
jalira-and-her-monsters-1.csv
jazz-hands-venser.csv
junkus-opus-primer-cedh-hulk-combo-copy.csv
kiki-aint-superstitious.csv
klothys-hates-your-lands.csv
konrad_twitty.csv
krenko-mob-boss-mobocracy.csv
last-voyage-of-the-weatherlight.csv
liliana-girls-and-zombies-1.csv
lurrus-artifact-aristocrats.csv
marchesa-queen-of-pain-77-altered.csv
melek-izzet-paragon-primer.csv
memnarch-grand-theft-permanents.csv
mishras-jank-machine.csv
mono-green-storm-og-budget-version.csv
my-homie-wizards-edh.csv
myrincubatordeck-1.csv
niv-mizzet-passive-ping-win.csv
noyan-dar-slow-roll.csv
nylea-keen-eyed-beef-chief.csv
obzedat-the-infinite-life-gain.csv
oh-lord-jesus-its-a-fire-neheb-edh.csv
old-men-from-the-forests-1.csv
olivia-voldaren-gala-of-gore.csv
omnath-cruel-gruul.csv
power-and-ruin-demon-tribal.csv
primer-kelsien-one-shot-one-kill.csv
queen-of-the-crop.csv
reaper-king-commander-of-all-the-little-folk.csv
saheelis-ironworks-kci.csv
saskias-blitzkrieg.csv
self-mill-combo-in-edh-psh-no-way.csv
sen-triplets-ultimate-domination-mh1-update-copy-1.csv
settle-it-with-a-swordfight.csv
should-i-pretend-this-or-that.csv
simic-moonfolk-landfall.csv
sith-mind-tricks.csv
sorin-bloodlust.csv
spy-cat-with-primer.csv
tawnos-technocracy.csv
teneb-the-boardwiper.csv
the-fat-red-line.csv
the-goddess-of-elves-1.csv
the-many-faced-god-primer-1.csv
the-necrogen-project.csv
the-sea-of-the-damned-theme-skel-shipgyruda-edh.csv
the-undisputed-rasputin.csv
theres-a-fungus-amogus.csv
today-i-will-cause-problems-on-purpose.csv
torbran-thane-of-incremental-damage.csv
traitor-of-men-sedris-graveyard-combo-edh.csv
untrue-colors.csv
we-brake-for-nobody.csv
web-of-the-spider.csv
what-is-dead-may-only-grow-more-heads.csv
wheelmaster-is-hot.csv
whos-that-hegemon.csv
win-a-game-lose-a-friend.csv
xira-arien-queen-of-the-swarm.csv
xyris-but-you-are-the-snake.csv
yahenni-there-are-benefits-to-dying.csv
yes-uril-can-primer.csv
youre-a-mean-one-mister-grinch.csv
zeus-god-of-control.csv

In [17]:
total_cards.describe()

            Name
count      22373
unique      4768
top     Sol Ring
freq         181

In [33]:
total_cards.describe()

            Name
count       6523
unique      2946
top     Sol Ring
freq          54

In [18]:
unique_cards = total_cards['Name'].unique()

In [19]:
unique_cards

array(['Adeline, Resplendent Cathar', "Angel of Glory's Rise",
       'Anointed Procession', ..., 'Ring of Three Wishes',
       'Sun Quan, Lord of Wu', "Tyrant's Familiar"], dtype=object)

In [20]:
!pip install requests

Requirement already satisfied: requests in c:\users\kaitlin\appdata\local\programs\python\python37\lib\site-packages (2.26.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\kaitlin\appdata\local\programs\python\python37\lib\site-packages (from requests) (2.0.9)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kaitlin\appdata\local\programs\python\python37\lib\site-packages (from requests) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\kaitlin\appdata\local\programs\python\python37\lib\site-packages (from requests) (1.26.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kaitlin\appdata\local\programs\python\python37\lib\site-packages (from requests) (3.3)

In [21]:
import requests
import csv
from time import sleep


url = "https://api.scryfall.com/cards/named?exact=CARDNAME"

payload={}
headers = {}
f1 = open('card_info.csv', 'w', encoding="utf-8")
writer1 = csv.writer(f1)

for card in unique_cards:
    response = requests.request("GET", url.replace("CARDNAME", card), headers=headers, data=payload)
    f1.write("{cardname},{cardinfo}\n".format(cardname=card, cardinfo=response.text))
    sleep(0.10)

In [22]:
card_nodes = pd.read_csv("card_info.csv")

ParserError: Error tokenizing data. C error: Expected 122 fields in line 29, saw 125