# Nodes Information

In [6]:
import pandas as pd

In [3]:
import json
 
# Opening JSON file
with open('card_info.json', encoding="utf-8") as json_file:
    data = json.load(json_file)

In [9]:
dataFrameHistorical = pd.DataFrame() 
dfItem = pd.DataFrame.from_records(data)               
dataFrameHistorical = dataFrameHistorical.append(dfItem, ignore_index=True)

In [26]:
 pd.DataFrame.from_dict(data).describe()

                                                    cards
count                                                4768
unique                                               4756
top     {'object': 'card', 'id': 'b5cb6da6-d43b-4ad1-b...
freq                                                    2

In [20]:
dataFrameHistorical = pd.DataFrame() 

for item in data['cards']:
    dfItem = pd.DataFrame.from_dict(item, orient='index')
    dfItem = dfItem.transpose()
    dataFrameHistorical = dataFrameHistorical.append(dfItem, ignore_index=True)

In [22]:
dataFrameHistorical.head()

,object,id,oracle_id,multiverse_ids,mtgo_id,arena_id,tcgplayer_id,cardmarket_id,name,lang,...,watermark,produced_mana,card_faces,promo_types,tcgplayer_etched_id,loyalty,color_indicator,printed_name,printed_type_line,printed_text
0,card,18092f68-b96e-4084-9eba-b240d2195d81,38515f89-348b-4cf3-b7bd-1f6fe4ce2fba,[534751],92916,78322,248137,574937,"Adeline, Resplendent Cathar",en,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,card,1865ab25-b01a-4e2c-bf19-ffcb0806358f,c6a606af-ea08-4cd9-bfd9-60d76e232e85,[539340],93574,NaN,248580,575359,Angel of Glory's Rise,en,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,card,9a52c265-6920-4929-ba0a-70da08df01f1,7246d45b-2185-4cdd-981b-5419b7d52bce,[426704],63606,NaN,130149,296825,Anointed Procession,en,...,planeswalker,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,card,46f17b66-2484-49f4-80db-408bfda95aa9,0bc7f093-bef0-4f1a-852c-4b75ebf54838,[545779],NaN,NaN,254178,584139,Arcane Signet,en,...,NaN,"[B, G, R, U, W]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,card,25ac5405-df7b-4097-914a-022cb18e20d4,c5acf2a5-40f4-433d-a74d-1cb56c521464,[522320],90869,NaN,238607,564641,Arid Mesa,en,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
dataFrameHistorical.to_csv("All_card_info_csv.csv")

In [24]:
dataFrameHistorical.describe()

,object,id,oracle_id,multiverse_ids,mtgo_id,arena_id,tcgplayer_id,cardmarket_id,name,lang,...,watermark,produced_mana,card_faces,promo_types,tcgplayer_etched_id,loyalty,color_indicator,printed_name,printed_type_line,printed_text
count,4768,4768,4768,4768,3707,994,4608,4574,4768,4768,...,326,817,103,27,23,89,8,3,2,2
unique,1,4756,4756,4729,3695,984,4596,4562,4756,4,...,30,42,92,7,23,7,5,3,2,2
top,card,609d3ecf-f88d-4268-a8d3-4bf2bcf5df60,868e6e68-4367-4073-a864-235d5961ae56,[],83175,73386,221830,12750,Malakir Rebirth // Malakir Mire,en,...,set,[C],"[{'object': 'card_face', 'name': 'Bala Ged Rec...",[planeswalkerdeck],240861,4,[U],Vigor,クリーチャー — デビル,先制攻撃\n発生源が対戦相手にダメージを与えるなら、それはその２倍のダメージを与える。
freq,4768,2,2,28,2,2,2,2,2,4765,...,60,180,2,7,1,33,2,1,1,1